#!/usr/bin/env python3

import unittest
import timer

class TestTransformWordFormToSeconds(unittest.TestCase):
    def test_transform_word_hours_to_seconds(self): 
        self.assertEqual(timer.transform_word_form_to_seconds('5h'), 18000)
        self.assertEqual(timer.transform_word_form_to_seconds('50h'), 180000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245h'), 4482000)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5h'), 181800)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455h'), 181638)
        self.assertEqual(timer.transform_word_form_to_seconds('0h'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5h'), 1800)

        self.assertEqual(timer.transform_word_form_to_seconds('5 h'), 18000)
        self.assertEqual(timer.transform_word_form_to_seconds('50 h'), 180000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245 h'), 4482000)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5 h'), 181800)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455 h'), 181638)
        self.assertEqual(timer.transform_word_form_to_seconds('0 h'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5 h'), 1800)

        self.assertEqual(timer.transform_word_form_to_seconds('5  h'), 18000)
        self.assertEqual(timer.transform_word_form_to_seconds('50  h'), 180000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245  h'), 4482000)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5  h'), 181800)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455  h'), 181638)
        self.assertEqual(timer.transform_word_form_to_seconds('0  h'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5  h'), 1800)

        self.assertEqual(timer.transform_word_form_to_seconds('5hours'), 18000)
        self.assertEqual(timer.transform_word_form_to_seconds('50hours'), 180000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245hours'), 4482000)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5hours'), 181800)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455hours'), 181638)
        self.assertEqual(timer.transform_word_form_to_seconds('0hours'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5hours'), 1800)

        self.assertEqual(timer.transform_word_form_to_seconds('5 час'), 18000)
        self.assertEqual(timer.transform_word_form_to_seconds('50 час'), 180000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245 час'), 4482000)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5 час'), 181800)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455 час'), 181638)
        self.assertEqual(timer.transform_word_form_to_seconds('0 час'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5 час'), 1800)

        self.assertEqual(timer.transform_word_form_to_seconds('5ч'), 18000)
        self.assertEqual(timer.transform_word_form_to_seconds('50ч'), 180000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245ч'), 4482000)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5ч'), 181800)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455ч'), 181638)
        self.assertEqual(timer.transform_word_form_to_seconds('0ч'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5ч'), 1800)

    def test_transform_word_minutes_to_seconds(self):
        self.assertEqual(timer.transform_word_form_to_seconds('5m'), 300)
        self.assertEqual(timer.transform_word_form_to_seconds('50m'), 3000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245m'), 74700)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5m'), 3030)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455m'), 3027)
        self.assertEqual(timer.transform_word_form_to_seconds('0m'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5m'), 30)

        self.assertEqual(timer.transform_word_form_to_seconds('5 m'), 300)
        self.assertEqual(timer.transform_word_form_to_seconds('50 m'), 3000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245 m'), 74700)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5 m'), 3030)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455 m'), 3027)
        self.assertEqual(timer.transform_word_form_to_seconds('0 m'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5 m'), 30)

        self.assertEqual(timer.transform_word_form_to_seconds('5     minutes'), 300)
        self.assertEqual(timer.transform_word_form_to_seconds('50     minutes'), 3000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245     minutes'), 74700)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5     minutes'), 3030)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455     minutes'), 3027)
        self.assertEqual(timer.transform_word_form_to_seconds('0     minutes'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5     minutes'), 30)

        self.assertEqual(timer.transform_word_form_to_seconds('5минут'), 300)
        self.assertEqual(timer.transform_word_form_to_seconds('50минут'), 3000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245минут'), 74700)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5минут'), 3030)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455минут'), 3027)
        self.assertEqual(timer.transform_word_form_to_seconds('0минут'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5минут'), 30)

        self.assertEqual(timer.transform_word_form_to_seconds('5 м'), 300)
        self.assertEqual(timer.transform_word_form_to_seconds('50 м'), 3000)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245 м'), 74700)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5 м'), 3030)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455 м'), 3027)
        self.assertEqual(timer.transform_word_form_to_seconds('0 м'), 0)
        self.assertEqual(timer.transform_word_form_to_seconds('0.5 м'), 30)

    def test_transfom_word_seconds_to_seconds(self):
        self.assertEqual(timer.transform_word_form_to_seconds('5s'), 5)
        self.assertEqual(timer.transform_word_form_to_seconds('50s'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245s'), 1245)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5s'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455s'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('0s'), 0)

        self.assertEqual(timer.transform_word_form_to_seconds('5   sec'), 5)
        self.assertEqual(timer.transform_word_form_to_seconds('50   sec'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245   sec'), 1245)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5   sec'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455   sec'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('0   sec'), 0)

        self.assertEqual(timer.transform_word_form_to_seconds('5  секу'), 5)
        self.assertEqual(timer.transform_word_form_to_seconds('50  секу'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245  секу'), 1245)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5  секу'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455  секу'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('0  секу'), 0)

        self.assertEqual(timer.transform_word_form_to_seconds('5с'), 5)
        self.assertEqual(timer.transform_word_form_to_seconds('50с'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('-1245с'), 1245)
        self.assertEqual(timer.transform_word_form_to_seconds('50,5с'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('50,455с'), 50)
        self.assertEqual(timer.transform_word_form_to_seconds('0с'), 0)

class TestTransformDigitFormToSeconds(unittest.TestCase):
    def test_result(self):
        self.assertEqual(timer.transform_digit_form_to_seconds('0:5:3'), 303)
        self.assertEqual(timer.transform_digit_form_to_seconds('00:5:3'), 303)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:15:3'), 903)
        self.assertEqual(timer.transform_digit_form_to_seconds('00:15:3'), 903)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:5:03'), 303)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:5:32'), 332)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:3'), 180)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:03'), 180)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:12'), 720)
        self.assertEqual(timer.transform_digit_form_to_seconds('00:12'), 720)
        self.assertEqual(timer.transform_digit_form_to_seconds('5:0'), 18000)
        self.assertEqual(timer.transform_digit_form_to_seconds('05:00'), 18000)
        self.assertEqual(timer.transform_digit_form_to_seconds('180:05'), 648300)
        self.assertEqual(timer.transform_digit_form_to_seconds('00:73:300'), 4680)
        self.assertEqual(timer.transform_digit_form_to_seconds('0:0:0'), 0)
        self.assertEqual(timer.transform_digit_form_to_seconds('2'), 7200)
        self.assertEqual(timer.transform_digit_form_to_seconds(':20'), 1200)
        self.assertEqual(timer.transform_digit_form_to_seconds(':15:4'), 904)

class TestPrintCurrentTime(unittest.TestCase):
    def test_result(self):
        self.assertEqual(timer.print_pretty_time(303), '00:05:03')
        self.assertEqual(timer.print_pretty_time(903), '00:15:03')
        self.assertEqual(timer.print_pretty_time(332), '00:05:32')
        self.assertEqual(timer.print_pretty_time(180), '00:03:00')
        self.assertEqual(timer.print_pretty_time(720), '00:12:00')
        self.assertEqual(timer.print_pretty_time(18000), '05:00:00')
        self.assertEqual(timer.print_pretty_time(648300), '180:05:00')
        self.assertEqual(timer.print_pretty_time(4680), '01:18:00')
        self.assertEqual(timer.print_pretty_time(0), '00:00:00')
        self.assertEqual(timer.print_pretty_time(7200), '02:00:00')
        self.assertEqual(timer.print_pretty_time(1200), '00:20:00')
        self.assertEqual(timer.print_pretty_time(904), '00:15:04')

if __name__ == '__main__':
    unittest.main()
